name: amanmemilih_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.14
  skeletons: ^0.0.3
  flutter_screenutil: ^5.9.3
  ua_client_hints: ^1.4.0
  equatable: ^2.0.5
  localization: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/launchers/
    - lib/core/lang/
