name: amanmemilih_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  bloc: ^8.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.14
  flutter_screenutil: ^5.9.3
  ua_client_hints: ^1.4.0
  equatable: ^2.0.5
  localization: ^2.1.1
  google_fonts: ^6.2.1
  camera: ^0.11.0+2
  camera_android_camerax: ^0.6.10
  image_editor_plus: ^1.0.6
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  image: ^4.5.4
  path_provider: ^2.1.5
  gal: ^2.3.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  awesome_snackbar_content: ^0.1.4
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/logo.png" # only available for Android 13 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - lib/core/lang/
